package BankingOperationsApp;


/**
* BankingOperationsApp/BankingOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankingOperations
* Wednesday, October 25, 2017 4:14:15 o'clock PM EDT
*/

public interface BankingOperations extends BankingOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BankingOperations
