package BankingOperationsApp;

/**
* BankingOperationsApp/BankingOperationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankingOperations
* Wednesday, October 25, 2017 4:14:15 o'clock PM EDT
*/

public final class BankingOperationsHolder implements org.omg.CORBA.portable.Streamable
{
  public BankingOperationsApp.BankingOperations value = null;

  public BankingOperationsHolder ()
  {
  }

  public BankingOperationsHolder (BankingOperationsApp.BankingOperations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankingOperationsApp.BankingOperationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankingOperationsApp.BankingOperationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankingOperationsApp.BankingOperationsHelper.type ();
  }

}
