package BankingOperationsApp;


/**
* BankingOperationsApp/custCountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankingOperations
* Wednesday, October 25, 2017 4:14:15 o'clock PM EDT
*/

public final class custCountHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public custCountHolder ()
  {
  }

  public custCountHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankingOperationsApp.custCountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankingOperationsApp.custCountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankingOperationsApp.custCountHelper.type ();
  }

}
